### ISSUE TITLE
PHP Warning: Use of undefined constant ...

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/integrity_check#120]
```
PHP Warning: Use of undefined constant install_count_check - assumed 'install_count_check' (this will throw an Error in a future version of PHP) in /home/bibo/contao4go/contao35/composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 197
#0 composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php(197): __error_enhanced(2, 'Use of undefined constant install_count_check - assumed 'install_count_check' (this will throw an Error in a future version of PHP)', 'composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php', 197, Array)
#1 system/modules/core/drivers/DC_Table.php(4701): BugBuster\IntegrityCheck\DcaIntegrityCheck->listChecks(Array, 'Integrity Check', Contao\DC_Table, Array)
#2 system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->listView()
#3 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('integrity_check')
#5 contao/main.php(20): Contao\BackendMain->run()

Warning: Use of undefined constant install_count_check - assumed 'install_count_check' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 215
```

**Comment by BugBuster1701** [comment]
Warning: Use of undefined constant check_plans - assumed 'check_plans' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 138

**Comment by BugBuster1701** [comment]
Warning: Use of undefined constant check_plans_expert - assumed 'check_plans_expert' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 139

**Comment by BugBuster1701** [comment]
Warning: Use of undefined constant id - assumed 'id' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 141

**Comment by BugBuster1701** [comment]
Warning: Use of undefined constant update_check - assumed 'update_check' (this will throw an Error in a future version of PHP) in composer/vendor/bugbuster/integrity_check/classes/DcaIntegrityCheck.php on line 197
